### ISSUE TITLE
Not getting notification

### ISSUE THREAD

**Issue by patelvishal1401** [smilefam/SendBird-Android#1]
I use this sdk, and tested in different devices, but not getting notifications.

Is there any change in project id or else.

**Comment by sf-jin-ku** [comment]
Hi Patel,
Could you send your APP_ID and account e-mail address to support@sendbird.com?
Thanks!

**Comment by patelvishal1401** [comment]
Yes, This is my app id : 322F9766-7907-4D18-9AEF-D218C2DD4650

**Comment by patelvishal1401** [comment]
Ok, sent, solve it as soon as possible. Thanks..
