### ISSUE TITLE
java.lang.SecurityException: Permission Denial: reading android.support.v4.content.FileProvider uri content://com.packagename.provider/external-path/FolderName/Image_20170207_152529.jpg from pid=0, uid=10008 requires the provider be exported, or grantUriPermission()

### ISSUE THREAD

**Issue by shishram** [smilefam/SendBird-Android#10]
in Helper class when uploading image from camera capture on below line i am getting above exception.
cursor = context.getContentResolver().query(uri, projection, selection, selectionArgs, null);

Let me know if any workaround is there

**Comment by terrykwon** [comment]
@shishram have you enabled permissions to read / write files for your app on your device?

**Comment by shishram** [comment]
Yes I have added already the problem was not running it on UI thread, but
this is fixed now. Thanks.

**Comment by terrykwon** [comment]
@shishram that's great to hear! I'll close the issue then.

**Comment by shishram** [comment]
Sure.
