### ISSUE TITLE
Delivery Receipt Support

### ISSUE THREAD

**Issue by ganeshub** [smilefam/SendBird-Android#14]
Hi,

Sendbird SDK supports Read receipt, but is it has support for Delivery receipt ?

**Comment by terrykwon** [comment]
@ganeshub We do not have delivery receipts. However, the SDK does receive a callback if a message was successfully sent to the servers.

```
mChannel.sendUserMessage(text, new BaseChannel.SendUserMessageHandler() {
    @Override
    public void onSent(UserMessage userMessage, SendBirdException e) {
    }
});
```

Also, you can check how many people have read a message with `groupChannel.getReadReceipt(message)`.
