### ISSUE TITLE
"400201: User not found" issue during SendBird.connect()

### ISSUE THREAD

**Issue by sujitpanda** [smilefam/SendBird-Android#16]
I am getting "400201 user not found" when connecting to sendbird using connect() method. Any idea why am i getting this issue ?

**Comment by terrykwon** [comment]
@sujitpanda Which version is this occurring on?

**Comment by sujitpanda** [comment]
I am using **SendBird SDK 3.0.22** . It is working fine in the demo app with the same version but when i integrating it to my app it is showing this "400201 : User Not Found" error .

**Comment by terrykwon** [comment]
@sujitpanda Does this happen when connecting as a certain user? Or all users? One possible cause might be that you are including whitespace in the user ID.

**Comment by sujitpanda** [comment]
@terrykwon No I have tried with so many users .  Same issue i am getting for all users. Do i need to create different app in the SendBird dashboard and get new API_KEY for using in different application . Currently i am using the same API_KEY that i used in the SendBird demo app .

**Comment by terrykwon** [comment]
Well, you ***should*** eventually create a new app that you can manage, but I don't think using the demo API key would cause an error when creating a user.

Could you share your code when you call `SendBird.connect()`? And could you double-check if you're getting the error in the `onConnected(User user, SendBirdException e)` callback or someplace else? Logs might be helpful!

**Comment by sagrawal2418** [comment]
I created a new test project and copy paste my code from actual project to new test project. In the new test project it is working absolutly fine but the same code not working in my existing project . onConnected() callback is getting called and then the SendBirdException is coming . Code is straightforward. Here is the code snippet .

```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        SendBird.init(appId, this);
        connect();
    }
 private void connect() {
        SendBird.connect(sUserId, new SendBird.ConnectHandler() {
            @Override
            public void onConnected(User user, SendBirdException e) {

                if (e != null) {
                    Toast.makeText(MainActivity.this, "" + e.getCode() + ":" + e.getMessage(), Toast.LENGTH_SHORT).show(); // This toast is getting shown with message "400201: User not found"
                    return;
                }
            }
        });
    }

Very strange issue. Is it someing related to my existing project dependencies ? becaue the exaxt code i have copy paste and it is working in new test app but not in existing app.
```

**Comment by sujitpanda** [comment]
I created a new test project and copy paste my code from actual project to new test project. In the new test project it is working absolutly fine but the same code not working in my existing project . onConnected() callback is getting called and then the SendBirdException is coming . Code is straightforward. Here is the code snippet .

```
private static final String appId = "C5****-*****-*****-******";

protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        SendBird.init(appId, this);
        connect();
    }
 private void connect() {
        SendBird.connect(sUserId, new SendBird.ConnectHandler() {
            @Override
            public void onConnected(User user, SendBirdException e) {

                if (e != null) {
                    Toast.makeText(MainActivity.this, "" + e.getCode() + ":" + e.getMessage(), Toast.LENGTH_SHORT).show(); // This toast is getting shown with message "400201: User not found"
                    return;
                }
            }
        });
    }
```

Very strange issue. Is it someing related to my existing project dependencies ? becaue the exaxt code i have copy paste and it is wokring in my new test app but not in existing app.

**Comment by sujitpanda** [comment]
My mistake . I was using GroupChannel.createChannelWithUserIds() and the id i was using for this  was missing/not created . That is why i was getting this error. Thanks.
