### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by cwfei** [smilefam/SendBird-Android#18]
Steps to reproduce:

1. Login
2. Create a group channel with any user
3. Switching between apps back and forth to triggered `onResume()` few times
4. Send a message
5. The recycler view will display the message twice

Video:
https://www.youtube.com/watch?v=d0v1Ut02050

**Comment by cwfei** [comment]
Yeah, `onMessageReceived` is being triggered on my own messages, which shouldn't happen.

**Comment by aftabsikander** [comment]
@terrykwon When you guys are planning to ship new release. Any timeline would be great.

**Comment by terrykwon** [comment]
@sf-jay-yun

**Comment by sf-jay-yun** [comment]
@aftabsikander Sorry for the belated response. We are digging the issue and expect the new release by next week.

**Comment by sf-jay-yun** [comment]
Thank you for the big patience. You can find that the latest version has resolved the issue.
