### ISSUE TITLE
Total unread messages count missing

### ISSUE THREAD

**Issue by andrzejchm** [smilefam/SendBird-Android#19]
Currently, the only place to get the total unread message count for a user is trough the push notification's payload. Within the Platform API documentation I can see that `User`'s payload does contain this data. Could we add a field for a user containing his total unread message count? Or at least a separate method to fetch it on demand from Android sdk.

**Comment by terrykwon** [comment]
You can do this with `GroupChannel.getTotalUnreadMessageCount()`.

> Gets the total number of unread message of all `GroupChannels` the current user has joined.

```
GroupChannel.getTotalUnreadMessageCount(new GroupChannel.GroupChannelTotalUnreadMessageCountHandler() {
        @Override
        public void onResult(int i, SendBirdException e) {
            if (e != null) {
                e.printStackTrace();
            }

            Log.d("GROUPCHANNEL", "Total unread message count: " + i);
        }
    });
```
