### ISSUE TITLE
how to share location?

### ISSUE THREAD

**Issue by achinverma** [smilefam/SendBird-Android#22]
Hi , i am using SendBird-Android SDK, https://docs.sendbird.com/android#quick_start.
please tell me how can i share the location using  SendBird-Android SDK like whatsapp ?

**Comment by sf-jay-yun** [comment]
Hi, big appreciate your long waiting.
Please refer to this page https://docs.sendbird.com/android#group_channel_3_sending_messages.
As you can see custom data field is provided when you send messages. If a sender sends a message with custom field having location information as json type or maybe other forms you want, on receiver side the custom field in the message can be parsed and you can use the information to render UI.

Hopes this helps.
Thanks.
