### ISSUE TITLE
Getting a crash after the app is minified due to enum InvitationState in class com.sendbird.android.Member

### ISSUE THREAD

**Issue by saurabhdtu** [smilefam/SendBird-Android#23]
Below is the crash report

> Fatal Exception: java.lang.AssertionError: java.lang.NoSuchFieldException: INVITED at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.(SourceFile) at com.google.gson.internal.bind.TypeAdapters$30.create(SourceFile:834) at com.google.gson.Gson.getAdapter(SourceFile:423) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:115) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:164) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:100) at com.google.gson.Gson.getAdapter(SourceFile:423) at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(SourceFile:53) at com.google.gson.Gson.getAdapter(SourceFile:423) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:115) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:164) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:100) at com.google.gson.Gson.getAdapter(SourceFile:423) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(SourceFile:115) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:164) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:100) at com.google.gson.Gson.getAdapter(SourceFile:423) at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(SourceFile:53) at com.google.gson.Gson.getAdapter(SourceFile:423) at retrofit2.converter.gson.GsonConverterFactory.responseBodyConverter(SourceFile:64) at retrofit2.Retrofit.nextResponseBodyConverter(SourceFile:330) at retrofit2.Retrofit.responseBodyConverter(SourceFile:313) at retrofit2.ServiceMethod$Builder.createResponseConverter(SourceFile:736) at retrofit2.ServiceMethod$Builder.build(SourceFile:169) at retrofit2.Retrofit.loadServiceMethod(SourceFile:170) at retrofit2.Retrofit$1.invoke(SourceFile:147) at java.lang.reflect.Proxy.invoke(Proxy.java:397) at $Proxy1.getTribes(Unknown Source) at com.threesixteen.app.controllers.GroupController.getGroups(SourceFile:124) at com.threesixteen.app.groups.GroupListFragment.getGroupList(SourceFile:210) at com.threesixteen.app.groups.GroupListFragment.access$000(SourceFile:55) at com.threesixteen.app.groups.GroupListFragment$4.onResponse(SourceFile:278) at com.threesixteen.app.groups.GroupListFragment$4.onResponse(SourceFile:268) at com.threesixteen.app.controllers.MatchController$21.onResponse(SourceFile:421) at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(SourceFile:70) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5254) at java.lang.reflect.Method.invoke(Method.java) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

The crash didn't occur on older versions. 
After debugging is seems your InvitationState enum is getting minified and thus resulting into the crash. 
Below I have attached the snippet of mapping with the minified mapping of your enum

```
com.sendbird.android.Member$InvitationState -> ms$a:
com.sendbird.android.Member$InvitationState INVITED -> a
com.sendbird.android.Member$InvitationState JOINED -> b
com.sendbird.android.Member$InvitationState[] $VALUES -> c
15:15:com.sendbird.android.Member$InvitationState[] values() -> values
15:15:com.sendbird.android.Member$InvitationState valueOf(java.lang.String) -> valueOf
15:15:void <init>(java.lang.String,int) -> <init>
15:16:void <clinit>() -> <clinit>

```
Request you to look into this issue, there might be other enums or classes too. 
Also request you to share an updated proguard rules for sendbird

**Comment by sf-jay-yun** [comment]
Thank you for the long waiting.
Please refer to this https://docs.sendbird.com/android#quick_start_4_4_configure_proguard_optional.
With this configuration on your proguard, the issue should be resolved.
