### ISSUE TITLE
Current user appearing in the select user list

### ISSUE THREAD

**Issue by AnIdioticMonkey** [smilefam/SendBird-Android#26]
The current user is displayed in the select user list, (i.e. blocking and creating a chat). Obviously the user shouldn't be able to create a chat with themselves, and due to the way i handle chat images could potentially cause a crash, so is there anyway to remove the current user from the list? I have tried creating an iterator and checking if the next value is equal to the current user but it never returns true for some reason. Am i missing something obvious?

Thanks!

**Comment by sf-jay-yun** [comment]
Hi,
Could you please confirm that you are comparing user ids?
If user.getUserId().equals(SendBird.getCurrentUser().getUserId()) returns true, you can regard the user is the current user.

**Comment by AnIdioticMonkey** [comment]
Sorry for the long reply, yeah i am using that method in the loadNextUserList, and it is not working. I feel as if it would work if it was in the loadInitialUserList however i do not know if i can compare the objects  returned from the query?

**Comment by sf-jay-yun** [comment]
Are you comparing user objects directly? SendBird.getCurrentUser() and User from UserListQuery are not same (more precisely, the memory address is different.) If you compare user Ids, by calling getUserId() from user object, it should work.

**Comment by AnIdioticMonkey** [comment]
Hi, i actually just got it to work by putting a for(User user : list) in the loadInitialUserList(), and comparing the user.getID() to the current users id. This successfully removes the current user from the list. However my next step was to remove specific users (i.e. head admins etc.), and i don't think this can be done this way? Comparing the user.getID() to a string seems to crash the app, is it possible to do  what i have suggested?
