### ISSUE TITLE
How we can remove other member from Group channel?

### ISSUE THREAD

**Issue by pkb126** [smilefam/SendBird-Android#27]
Greeting,

I want to remove other member from group, How i can?

How group invitation work? Please update the document with working scenario.

**Comment by sf-tyler-jeong** [comment]
Sorry for the late reply.

You can use Platform API.
=> https://docs.sendbird.com/platform#group_channel_3_leave_the_channel

Thank you.

**Comment by sf-jay-yun** [comment]
@pkb126 as @sf-tyler-jeong mentioned above, if you want to remove other members from group channel, it can be done only by Platform API. (Or on the member side, you can call channel.leave() but I don't think this is your case.)

And for invitation, you can refer to https://docs.sendbird.com/android#group_channel_3_inviting_users_to_an_existing_channel

**Comment by pkb126** [comment]
Thank you @sf-jay-yun and @sf-tyler-jeong
