### ISSUE TITLE
Open group channel from channel url

### ISSUE THREAD

**Issue by Jevisa** [smilefam/SendBird-Android#29]
I can't understand what is the problem, when i'm <code>GroupChannel.getChannel</code> from channel url, show message exception

The error code : 800130
The message : <code>com.c.a.a.a.a.a.d.d: Use JsonReader.setLenient(true) to accept malformed JSON at line 3 column 12 path $</code>

anyone can help me, thanks

**Comment by sf-jay-yun** [comment]
Hi, if you are using minifyEnabled as true, have you tried the guide https://docs.sendbird.com/android#quick_start_4_strong_step_4__strong_configure_proguard_em_optional_em ?

**Comment by Jevisa** [comment]
@sf-jay-yun i'm already add progruad-rules, but the message exception still appear

**Comment by sf-jay-yun** [comment]
Could you share the application ID?

**Comment by Jevisa** [comment]
@sf-jay-yun <code>D74864D6-2283-48E1-8381-89719216DC7F</code>

**Comment by sf-jay-yun** [comment]
Ah, the channel url the error occurs, could you share it too, please?

**Comment by Jevisa** [comment]
@sf-jay-yun <code>sendbird_group_channel_53542781_ca409adf8f8a865494aa984094531489d9c0fe44</code> and the userId <code>4308721</code>

**Comment by sf-jay-yun** [comment]
Thanks for the information. Will get back to you after the investigation.

**Comment by sf-jay-yun** [comment]
@Jevisa The channel url you shared does not exist. And user 4308721 does not belong to any channel now. The error seems to occur because you call invalid getChannel. Only channel members call getChannel and get the correct response. Regarding the error currently occurring, though, we will fix on server side to return in a correctly formed error.

**Comment by Jevisa** [comment]
@sf-jay-yun ok thanks for response sir
