### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by tartacutza** [smilefam/SendBird-Android#3]
Hi, how does one remove the user token at sign out? I'm trying to keep the app from receiving notifications and not just filter when to display them. I see there's a method for the iOS SDK "unregisterDeviceToken" but I can't seem to find an equivalent in the Android SDK. Can you please help?

**Comment by sf-jay-yun** [comment]
If you are using SDK v3, SendBird.unregisterPushTokenAllForCurrentUser(UnregisterPushTokenHandler handler);
SendBird.unregisterPushTokenForCurrentUser(String gcmRegToken, UnregisterPushTokenHandler handler);
might be the ones you want.
Please refer to the below document.
https://docs.sendbird.com/android#push_notifications

In SDK v2, SendBird.unregisterAllDevicesPushToken(UnregisterPushTokenHandler handler); and SendBird.unregisterCurrentDevicePushToken(UnregisterPushTokenHandler handler);  are the counterpart of the above.
