### ISSUE TITLE
Can't received notification and message when onPause in android

### ISSUE THREAD

**Issue by Jevisa** [smilefam/SendBird-Android#32]
I'm use fcm to handle notification, when app destroy, notification received well, but when app in background (<code>onPause</code>) android, i can't received notification, how to handle it? and the another problem when i back to onResume i'm can't received new messages has been send. i'm already init <code>SendBird.refresh()</code> in <code>onResume</code>

**Comment by sf-tyler-jeong** [comment]
Sorry for the late reply.

Please try to check the issue in latest sample.
You can use ConnectionManager for connection management in latest sample.

Also you can receive push notification when disconnected status only.
Please check if you are using setAutoBackgroundDetection(true). (default: true)
If setAutoBackgroundDetection(true), when app in background(onPause()), app will be in disconnected status and you can receive push notification.

If you want to show new messages when onResume(), You must call getPreviousMessagesByTimestamp() after GroupChannel.refresh().

Thank you.
