### ISSUE TITLE
Unable to receive push notification on V3

### ISSUE THREAD

**Issue by always-akshat** [smilefam/SendBird-Android#4]
i have followed all the steps for implementing GCM push notifications, but i still didn't receive any push in my onReceive() method. It didn't work for me on the sample Android app after changing the appId. 
1. added google GCM senderId, API key to the sendbird dashboard.
2. registered my gcm token via registerPushTokenForCurrentUser() in onConnected() callback of Sendbird.connect()
3. implemented GCM receiver and implemented parsing of data from gcm push.

**Comment by sf-jay-yun** [comment]
You can receive push notification only in disconnected state.
Before v3.0.2, SendBird.disconnect() should be called when your application goes background, which may be the case you want push notification to be received.

From v3.0.2, SendBird SDK automatically tracks the applications' state whether they are foreground or not and changes connection state accordingly. So you don't have to call disconnect() explicitly when your application goes background.

Please refer to the below updated document page.
https://docs.sendbird.com/android#push_notifications
