### ISSUE TITLE
Connect a user to a SendBird server using their User ID

### ISSUE THREAD

**Issue by manetivinay** [smilefam/SendBird-Android#49]
I have followed this doc till step number 2 and executed the code

https://docs.sendbird.com/android#4_strong_step_2__strong_connect_to_sendbird_server

```
SendBird.connect(String.valueOf(UserManagement.getInstance().getCurrentLoggedInUserId()), (user, e) -> {
                    if(e != null) {    // Error.
                        Log.d(TAG, "failure sendbird " + e.getCode() + " " + e.getMessage());
                        Toast.makeText(DashboardActivity.this, "failure sendbird " + e.getCode() + " " + e.getMessage(), Toast.LENGTH_SHORT).show();
                        return;
                    }

                    Toast.makeText(DashboardActivity.this, "Successfully sendbird ", Toast.LENGTH_SHORT).show();
                });
```

and the response i'm getting into error

`code : 800102  Message: Connection has been canceled`

and I have seen  doc's

```ERR_CONNECTION_CANCELED | 800102 | The connection is cancelled or the disconnecting method is called while the SendBird object is trying to connect to the server via the connecting method.```

on Android platform can you be please help me with the above problem.

**Comment by manetivinay** [comment]
It's working now

**Comment by obuck** [comment]
How did you fix it?
