### ISSUE TITLE
Push notifications not working with FCM

### ISSUE THREAD

**Issue by marcosPerezRubio** [smilefam/SendBird-Android#5]
Hello,

I'm making a chat app with push notifications with new Firebase Cloud Messagin SDK and SendBird SDK.

As i have stated, i can receive pusn notifications from FCM dashboard but no the SendBord one despite the token is registered and sendbird is connected. 

I saw that the callback provided in sendbird documentation for the message received method for the gcm is different than rhe new provided in fcm.

Is this normal behaviour right now? Maybe i missed something but this thing about the callback name, makes me think that there is a problem.

In case I'm right, is there any release Date for the update?

Thanks a lot!

**Comment by sf-jay-yun** [comment]
Hi,

New sample working with FCM is now available.

Many thanks!
