### ISSUE TITLE
No valid Api-Token

### ISSUE THREAD

**Issue by DobrinAlexandru** [smilefam/SendBird-Android#6]
One of my devies One plus 2(6.1.0) keeps send "no valid api token" error code 400401.
How can i set the api token in the sdk?

**Comment by sf-jay-yun** [comment]
Do you see the problem when you run this sample on the device?

The error code means that connection is not successfully set.
When you call SendBird.connect() please verify that the connection is established by checking the error object is null on ConnectHandler.onConnected().

**Comment by CongBaDo** [comment]
I faced this problem too, how to solve it

**Comment by sf-jay-yun** [comment]
@CongBaDo Do you call SendBird related method after confirming SendBird.connect() is successfully finished? You can check it with ConnectHandler, which calls back error with null if connection is established well.

**Comment by fabdousse** [comment]
Hi ! I have this problem also since I tried to put push notifications. How come ?
 Thank you !

**Comment by sf-jay-yun** [comment]
@fabdousse When you open a push notification and want to do something with SendBird SDK, please make sure that SendBird.connect() is called and ConnectHandler is called back with null error.
